spring.thymeleaf.check-template-location=false
spring.thymeleaf.check-template-location=false
spring.thymeleaf.check-template-location=false
spring.thymeleaf.check-template-location=false

spring.thymeleaf.check-template-location=false
agregado
spring.thymeleaf.check-template-location=false
spring.thymeleaf.check-template-location=false
spring.thymeleaf.check-template-location=false

